### ISSUE TITLE
Compiled builds of VBA-M for Wii/Wii U (Libretro) show only a white screen on all emulated games.

### ISSUE THREAD

**Issue by saulfabregwiivc** [libretro/vbam-libretro#115]
### Expected behavior

I expected in the compiled builds for Wii / Wii U (Libretro/RetroArch) to display the screens of the emulated games (title screens, intros, actual gameplay, etc.)

### Actual behavior

On all tested games, it just display a white screen. (Video driver issues on VBA-M Libretro for these consoles? Wii / Wii U?)
I even asked to main VBA-M developers ( https://github.com/visualboyadvance-m/visualboyadvance-m/issues/1170 ) and they think it's related to big endian issues :P

GB/GBC:

![image](https://user-images.githubusercontent.com/66485640/260822589-7e0592b7-bc3f-4b2f-a2be-253e31be6ef7.png)

GBA:

![image](https://user-images.githubusercontent.com/66485640/260822650-edc60c9d-4f73-4f97-8028-03d7b5c45e9e.png)

### Steps to reproduce the behavior

1. Compile a build of VBA-M as a Libretro core for Wii or Wii U as usual (enter to **vbam_libretro_source/src/libretro** folder and run **make platform=wii** or **make platform=wiiu**)
2. Run the compiled build from RetroArch on Wii or Wii U (depending of the system you have built the core)
3. Load any game (GB, SGB, GBC, GBA)
4. The game will only display a white screen

### Crash bugs

None. Just a white screen, no error messages.

### ROM details

Which games are affected by the issue (please state if GBA or GB game):

All GB/GBC/GBA games, inlcluding SGB ones, are affected by this issue (white screen instead of game screens.)

Even trying to use BIOS is useless since it doesn't even display the BIOS intro (white screen).

### Option details

Video driver (simple, opengl): Don't know cause i was trying on Wii (gx)

Sound driver (directsound, xaudio, openal, SDL): Don't know cause i was trying on Wii (gx)

### Build details

VBA-M: latest VBA-M Libretro until git https://github.com/libretro/vbam-libretro/commit/640ce45325694d1dc574e90c95c55bc464368d7e
OS: Wii / Wii U (Libretro / RetroArch)

**Comment by saulfabregwiivc** [comment]
Made a PR which will fix these issues. https://github.com/libretro/vbam-libretro/pull/116

**Comment by negativeExponent** [comment]
why not just replace WORDS_BIGENDIAN to MSB_FIRST in the codebase to make this more consistent?
