### ISSUE TITLE
Enable Super Game Boy use in VBA-M Module

### ISSUE THREAD

**Issue by Zombie-Ryushu** [libretro/vbam-libretro#15]
RetroArch should not rely on bsnes-mercury for Super Game Boy Support. It should use the Super Game Boy support incuded in VBA-M. RetroArch is not practical for Super Game Boy Support currently. SDL Mode builds of RetroArch do support Super Game Boy.

**Comment by sergiobenrocha2** [comment]
This is a messy feature also: https://sourceforge.net/p/vbam/bugs/150/

**Comment by Zombie-Ryushu** [comment]
This is still an issue as BSNES Super Game Boy Support is Windows Only.

**Comment by milesrotaru** [comment]
Hack for borders and colors is better than nothing, especially on Android and other platforms where the bsnes method for SGB emulation is not an option.

**Comment by nikkoman** [comment]
I would suggest a separate core built exclusively for SGB (border & colour) emulation, as there is no other option for low-powered devices.

External borders are not real emulation and SGB colours for games such as Mighty Morphin' Power Rangers make them have a reason to exist.

**Comment by retro-wertz** [comment]
sgb should now be possible in latest commit. just dont expect it to have snes sounds though as that requires separate emulation for the snes apu. 2/4 player mode and borders should work (not sure what else can sgb do atm)

**Comment by hizzlekizzle** [comment]
Closing this issue, since the task is complete. Feel free to reopen if necessary.

**Comment by Zombie-Ryushu** [comment]
Confirmed to be working.
