### ISSUE TITLE
Add Support for External BIOS Files

### ISSUE THREAD

**Issue by Awakened0** [libretro/vbam-libretro#17]
Stand alone VBA-M has the ability to load GB, GBC and GBA BIOS images. I don't think you'd need a core option for enabling them or not, they could just autoload if they are present in the System folder like some of the other cores. "Skip boot logo" could be useful as a core option for when you're using a BIOS though.

**Comment by grantgalitz** [comment]
BIOS loading should be an option always... It's *not* loading a bios file that's an HLE type hack. For accuracy fans the BIOS must be an option.

**Comment by Oggom** [comment]
Accuracy fans should avoid VBA at all costs.

**Comment by retro-wertz** [comment]
added as a core option
https://github.com/libretro/vbam-libretro/pull/42

**Comment by Awakened0** [comment]
Thanks!
