### ISSUE TITLE
Random crashes at startup

### ISSUE THREAD

**Issue by fr500** [libretro/vbam-libretro#19]
This commit causes random crashes on windows x64, I bisected and as weird as it is it's the first broken commit.

https://github.com/libretro/vbam-libretro/commit/a7d9a2ad07902d4eddfac1f6ca2cb3f99085d834

Also, now that input remapping options are working, maybe I should revert my alternate mappings commits?

**Comment by Tatsuya79** [comment]
It crashes all the time now on win7 x64.
Reverting that commit didn't help.

Killing everything about controller_layout and emptying retro_set_controller_port_device makes it work again.

**Comment by retro-wertz** [comment]
this should not be a problem with latest commit, latest in upstream  has this alternate layouts removed as well (should just use api to remap, for now...)
