### ISSUE TITLE
Cheats not working

### ISSUE THREAD

**Issue by waitingmoon** [libretro/vbam-libretro#28]
All cheat does not work. The game I'd like to apply cheat is "Battle Network Rockman EXE 3 - Black (J) (V1.1)", but the cheat for this game was not available from "Online Updater". So I tried trying to make that myself by referring to the cheat file for other games ...

cheats = "3"
cheat1_desc = "Bug Piece 9999"
cheat1_code = "02001DCA+FF"
cheat1_enable = "true"
cheat2_desc = "Bug Piece 9999"
cheat2_code = "1AFD2C72+93B8AC84
cheat2_enable = "true"
cheat3_desc = "Bug Piece 9999"
cheat3_code = "32001DCA+00FF"
cheat3_enable = "true"

From the top, Raw, Gameshark (v1 / 2) / Action Replay, CodeBreaker format.

I have confirmed that the code is correct with the standalone version of VBA-M.

**Comment by retro-wertz** [comment]
cheats should already be working with this core...

**Comment by retro-wertz** [comment]
cheats should be working now in latest commit both for gb/gbc and gba and multiline-cheats
