### ISSUE TITLE
The core options should be ON and OFF toggles, not "Yes" and "No"

### ISSUE THREAD

**Issue by hyarsan** [libretro/vbam-libretro#35]

**Comment by retro-wertz** [comment]
should be fixed here:
https://github.com/libretro/vbam-libretro/pull/42

**Comment by retro-wertz** [comment]
this should already be on/off toggles with latest commit....

**Comment by retro-wertz** [comment]
this has been already an on/off toggle awhile back...

**Comment by hizzlekizzle** [comment]
Closing this issue, since the task is complete. Feel free to reopen if necessary.
