### ISSUE TITLE
[Request] vbam core for iOS

### ISSUE THREAD

**Issue by illando** [libretro/vbam-libretro#68]
Would be possible to compile a version of the vbam core for iOS?
It seems to be one of the few core with gyroscope emulation, and would be great to play that type of games on iPhone.

Thanks.

**Comment by ZachBacon** [comment]
Already possible.

**Comment by illando** [comment]
That is great to know.
But it seems not included in the Retroarch for iOS version. There are:Meteor, mGBA, VBA Next and BettleGBA, but not VBAm.

![image](https://user-images.githubusercontent.com/11694410/62473219-98ef9800-b7a0-11e9-9fac-35cdd38701db.png)

**Comment by ZachBacon** [comment]
Oh, so what you are requesting is for retroarch to provide the core. I gotcha, because it sounded like you were asking for iOS support which technically it does have support for it.

**Comment by illando** [comment]
@ZachBacon Thanks for your reply.
I'm sorry but I'm a little bit confused. Are you suggesting that this is not the right place to post issue about VBAm for the iOS version of Retroarch? Is there a better place to talk only about Retroarch for iOS?. I posted here because I supposed it's a problem related to this core.

**Comment by retro-wertz** [comment]
ios9/ios-generic should have the vbam available, im just not sure which device would have this....
![Screenshot_2019-08-07_19-12-21](https://user-images.githubusercontent.com/23315382/62618655-56b48b00-b947-11e9-8501-49b0989f48f4.png)

**Comment by illando** [comment]
Yep ! I can confirm that now it's working (Retroarch 1.8.4)
