### ISSUE TITLE
[Request] Autohold buttons and autofire in Retroach core

### ISSUE THREAD

**Issue by Deivmsr** [libretro/vbam-libretro#79]
I noticed these commits on the official vba-m standalone github and was wondering if there would be a possibility to bring them to the core of Retroarch. I was interested to see how autohold buttons work on Android.

Here are the links to the github commits of the standalone version of vba-m:
Autohold buttons:
https://github.com/visualboyadvance-m/visualboyadvance-m/commit/03121c69c0f5267cffd9a88112fcc088272b3f07

Autofire:
https://github.com/visualboyadvance-m/visualboyadvance-m/commit/cf47942f09b92a256ed2c3a90962d6fae2adc3d1

**Comment by negativeExponent** [comment]
this is probably better to be impletemented on the frontend (RA) rather on the cores...

**Comment by hizzlekizzle** [comment]
This is indeed a frontend issue. Closing
