### ISSUE TITLE
Cannot get past the title screen of Yoshi (GB)

### ISSUE THREAD

**Issue by ds22x** [libretro/vbam-libretro#83]
### Expected behavior
Get past title screen when pressing a button.
### Actual behavior
No input gets recognized whatsoever.
### Steps to reproduce the behavior
Launch the rom with default configuration through Retroarch.
### ROM details

Which games are affected by the issue (please state if GBA or GB game):
Yoshi for Gameboy from the No-Intro romset.
### Option details

Video driver (simple, opengl): OpenGL, Vulkan.

Sound driver (directsound, xaudio, openal, SDL): OpenSL.

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Android.

Version of code (pre-built binary version, or commit ref, or just "master"): Master.

**Comment by negativeExponent** [comment]
huh... more serial io emulation issues here. i can fix Yoshi but Alleyway now breaks. i'll see if i can do a proper fix on this when i have more time (despite the isolation, im still busy-in some way :D)

**Comment by negativeExponent** [comment]
ill send PR soon to fix this... If you have noticed any other games that behave similarly, please post them here.

**Comment by negativeExponent** [comment]
this should be fixed in this PR https://github.com/libretro/vbam-libretro/pull/99
