### ISSUE TITLE
[Request] VBA-M core for 3DS

### ISSUE THREAD

**Issue by sks316** [libretro/vbam-libretro#84]
Self-explanatory.
Most of my library seems to crash with gpSP and I've had no issues with VBA-M on other platforms, and I have a ROM that only works with VBA-M regardless of platform.

**Comment by negativeExponent** [comment]
vba-m would be too slow for 3DS without dynarec or threading. try vba-next if its available. if you need something fixed (unless its performance related) then post on the related core's issue page and ill see (or someone else) if we can push a fix or near better working condition for it.

or you can post issue for gpSP and probably that can be fixed.
