### ISSUE TITLE
Games with cartridge type 0xFE fail to create a save and RTC file

### ISSUE THREAD

**Issue by ds22x** [libretro/vbam-libretro#95]
Specifically Robopon - Sun Version and its Japanese sister games suffer from this problem.
The games will successfully create a save and RTC file when using Sameboy.

**Comment by negativeExponent** [comment]
not sure you closed this.. But i did some test. HuC3 can at lease save and load game, battery detect was just not enabled. Not sure if its complete though. As for RTC, its not implemented but i believe the registers to advance time is there, and possibly included in savestate variables.

**Comment by ds22x** [comment]
Reopened because I honesly can't remember why I closed it in the first place.

**Comment by negativeExponent** [comment]
pushed a PR to enable save support. Also updated rtc support, this should allow keeping time  in sync with host time. You need to set initial time of the game at first though, as it starts in Year 2000.

Havent tested far enough into the game, but checking if time is still in sync and if load/save works seems ok enough and working. 

https://github.com/libretro/vbam-libretro/pull/102
